#include <fontconfig/fontconfig.h>
const int fcSlant[] = {FC_SLANT_ROMAN, FC_SLANT_ITALIC, FC_SLANT_OBLIQUE, };
const int fcWeight[] = {FC_WEIGHT_THIN, FC_WEIGHT_EXTRALIGHT, FC_WEIGHT_ULTRALIGHT, FC_WEIGHT_LIGHT, FC_WEIGHT_BOOK, FC_WEIGHT_REGULAR, FC_WEIGHT_NORMAL, FC_WEIGHT_MEDIUM, FC_WEIGHT_DEMIBOLD, FC_WEIGHT_SEMIBOLD, FC_WEIGHT_BOLD, FC_WEIGHT_EXTRABOLD, FC_WEIGHT_ULTRABOLD, FC_WEIGHT_BLACK, FC_WEIGHT_HEAVY, FC_WEIGHT_EXTRABLACK, FC_WEIGHT_ULTRABLACK, };
const int fcWidth[] = {FC_WIDTH_ULTRACONDENSED, FC_WIDTH_EXTRACONDENSED, FC_WIDTH_CONDENSED, FC_WIDTH_SEMICONDENSED, FC_WIDTH_NORMAL, FC_WIDTH_SEMIEXPANDED, FC_WIDTH_EXPANDED, FC_WIDTH_EXTRAEXPANDED, FC_WIDTH_ULTRAEXPANDED, };
